### ISSUE TITLE
Rendere i pacchetti .apk disponibili in download senza PlayStore

### ISSUE THREAD

**Issue by strk** [teamdigitale/italia-app#186]
Renderli scaricabili da GitHub dovrebbe essere la cosa piu' semplice.
Includerli in http://f-droid.org sarebbe auspicabile.

**Comment by cloudify** [comment]
Ciao @strk si assolutamente, abbiamo già una pipeline di CI su CircleCI, pubblicare delle nightly build è "tra le cose da fare" ™️ !

**Comment by cloudify** [comment]
Una volta fatto il merge della #251 gli apk saranno disponibili tra gli artifacts su [circleci](https://circleci.com/gh/teamdigitale/italia-app)

**Comment by cloudify** [comment]
La #251 è merged, chiudo

**Comment by Kezii** [comment]
Gli artifacts non sono sempre disponibili nella CI che ora è linkata nel readme, e in ogni caso bisogna registrarsi al servizio, non si possono pubblicare gli apk in maniera più ufficiale?

**Comment by giupardeb** [comment]
@cloudify non sarebbe una brutta idea usare la stessa politica sfruttata da Signal (https://signal.org/android/apk/)
