### ISSUE TITLE
Notifica di benvenuto

### ISSUE THREAD

**Issue by spiunno** [teamdigitale/italia-app#414]
**Descrivi il problema**
Quando l'applicazione viene aperta la prima volta, subito dopo l'installazione, nella sezione Messaggi non c'è niente.   Per risolvere il problema si dovrebbe ricevere immediatamente una notifica auto-generata dal sistema la quale ti da il benvenuto e ti spiega le prime cose utili.

Forse bisognerebbe mandare anche 3-4 notifiche demo che servano da esempio, tipo una che proviene da "Il tuo Comune", una da "La tua Regione", etc.  - il fatto che sono solo esempi deve essere chiaramente visibile e il testo dovrebbe dire "un giorno, quando l'integrazione sarà attivata, qui troverai  etc etc".

**Comment by cloudify** [comment]
Grazie per la issue, questa feature è [work in progress](https://www.pivotaltracker.com/story/show/159003198)
