### ISSUE TITLE
l'app va in crash annullando l'inserimento di una nuova cc

### ISSUE THREAD

**Issue by gunzip** [teamdigitale/italia-app#571]
Dopo aver compilato il form per l'inserimento dei dati della carta di credito e aver cliccato su "continua"
se si seleziona "annulla" nella schermata "vuoi salvare questa carta ?" l'app va in crash

![ezgif-5-19c2745f61](https://user-images.githubusercontent.com/148224/46105586-b47c3080-c1d6-11e8-971e-a50077c66a39.gif)

 - Device: Huawei p7
 - OS: Android

**Comment by cloudify** [comment]
https://www.pivotaltracker.com/story/show/160804645

**Comment by cloudify** [comment]
Fixed by https://github.com/teamdigitale/italia-app/pull/576
